ALTER TYPE "SaleOrderStatus" RENAME VALUE 'PRODUCTION_READY' TO 'FITTING_READY';
ALTER TYPE "SaleOrderStatus" RENAME VALUE 'IN_PRODUCTION' TO 'IN_FITTING';

ALTER TYPE "SaleOrderStatusSource" RENAME VALUE 'PRODUCTION' TO 'FITTING';

ALTER TYPE "InventoryItemStatus" RENAME VALUE 'IN_PRODUCTION' TO 'IN_FITTING';

UPDATE "SaleOrderStatusLog"
SET "fromStatus" = CASE "fromStatus"
  WHEN 'PRODUCTION_READY' THEN 'FITTING_READY'
  WHEN 'IN_PRODUCTION' THEN 'IN_FITTING'
  ELSE "fromStatus"
END
WHERE "fromStatus" IN ('PRODUCTION_READY', 'IN_PRODUCTION');

UPDATE "SaleOrderStatusLog"
SET "toStatus" = CASE "toStatus"
  WHEN 'PRODUCTION_READY' THEN 'FITTING_READY'
  WHEN 'IN_PRODUCTION' THEN 'IN_FITTING'
  ELSE "toStatus"
END
WHERE "toStatus" IN ('PRODUCTION_READY', 'IN_PRODUCTION');

UPDATE "Permission"
SET "subject" = 'fitting'
WHERE "subject" = 'production';
